title: "Agentic AI for Earth Observation"
description: "The workshop for agentic AI and earth observation in Berlin, Germany, 19-21 October 2026"
baseurl: ""
url: ""
hero_image: /assets/images/backgrounds/Agentic_AI_EO_footer_1024x160.png
og_image: /assets/images/backgrounds/Agentic_AI_EO_keyvisual_260506.png
venue_name: "Langenbeck-Virchow-Haus"
venue_address: |
  Luisenstraße 58/59<br>
  10117 Berlin, Mitte

contact_email: "contact@agentic-eo.berlin"
paper_email: "paper@agentic-eo.berlin"
demo_email: "demo@agentic-eo.berlin"
hands_on_email: "hands-on@agentic-eo.berlin"

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
